from typing import Dict, Type

from app.models import (
    IcarAnimalCoreResource,
    IcarMovementBirthEventResource,
    IcarWeightEventResource,
    IcarTreatmentEventResource,
    IcarTreatmentProgramEventResource,
    IcarGroupWeightEventResource,
    IcarMovementArrivalEventResource,
    IcarMovementDepartureEventResource,
    IcarMovementDeathEventResource,
    IcarAnimalSetJoinEventResource,
    IcarAnimalSetLeaveEventResource,
    IcarGroupTreatmentEventResource,
    IcarReproInseminationEventResource,
    IcarMilkingVisitEventResource,
    IcarAnimalSetResource,
    GenericIcarResource,
    IcarResource,
    IcarAttentionEventResource,
    IcarDiagnosisEventResource,
    IcarHealthStatusObservedEventResource,
    IcarRemarkEventResource,
    IcarWithdrawalEventResource,
    IcarFeedResource,
    IcarFeedStorageResource,
    IcarFeedTransactionResource,
    IcarFeedIntakeEventResource,
    IcarFeedRecommendationResource,
    IcarFeedReportResource,
    IcarRationResource,
    IcarGroupFeedingEventResource,
    IcarReproAbortionEventResource,
    IcarReproDoNotBreedEventResource,
    IcarReproEmbryoFlushingEventResource,
    IcarReproEmbryoResource,
    IcarReproHeatEventResource,
    IcarReproMatingRecommendationResource,
    IcarReproParturitionEventResource,
    IcarReproPregnancyCheckEventResource,
    IcarReproSemenStrawResource,
    IcarReproStatusObservedEventResource,
    IcarGestationResource,
    IcarLactationResource,
    IcarLactationStatusObservedEventResource,
    IcarMilkingDryOffEventResource,
    IcarDailyMilkingAveragesResource,
    IcarMilkPredictionResource,
    IcarTestDayResource,
    IcarTestDayResultEventResource,
    IcarCarcassResource,
    IcarCarcassObservationsEventResource,
    IcarBreedingValueResource,
    IcarProgenyDetailsResource,
    IcarGroupMovementBirthEventResource,
    IcarGroupMovementArrivalEventResource,
    IcarGroupMovementDepartureEventResource,
    IcarGroupMovementDeathEventResource,
    IcarPositionObservationEventResource,
    IcarGroupPositionObservationEventResource,
    IcarDeviceResource,
    IcarMedicineResource,
    IcarMedicineTransactionResource,
    IcarLocationResource,
    IcarInventoryTransactionResource,
    IcarObservationSummaryResource,
    IcarProcessingLotResource,
    IcarStatisticsResource,
    IcarSchemeTypeResource,
    IcarSchemeValueResource,
    IcarSortingSiteResource,
    IcarAnimalSortingCommandResource,
    IcarConformationScoreEventResource,
    IcarTypeClassificationEventResource,
)

RESOURCE_MODEL_REGISTRY: Dict[str, Type[IcarResource]] = {
    "icarAnimalCoreResource": IcarAnimalCoreResource,
    "icarMovementBirthEventResource": IcarMovementBirthEventResource,
    "icarWeightEventResource": IcarWeightEventResource,
    "icarTreatmentEventResource": IcarTreatmentEventResource,
    "icarTreatmentProgramEventResource": IcarTreatmentProgramEventResource,
    "icarGroupWeightEventResource": IcarGroupWeightEventResource,
    "icarMovementArrivalEventResource": IcarMovementArrivalEventResource,
    "icarMovementDepartureEventResource": IcarMovementDepartureEventResource,
    "icarMovementDeathEventResource": IcarMovementDeathEventResource,
    "icarAnimalSetJoinEventResource": IcarAnimalSetJoinEventResource,
    "icarAnimalSetLeaveEventResource": IcarAnimalSetLeaveEventResource,
    "icarGroupTreatmentEventResource": IcarGroupTreatmentEventResource,
    "icarReproInseminationEventResource": IcarReproInseminationEventResource,
    "icarMilkingVisitEventResource": IcarMilkingVisitEventResource,
    "icarAnimalSetResource": IcarAnimalSetResource,
    "icarAttentionEventResource": IcarAttentionEventResource,
    "icarDiagnosisEventResource": IcarDiagnosisEventResource,
    "icarHealthStatusObservedEventResource": IcarHealthStatusObservedEventResource,
    "icarRemarkEventResource": IcarRemarkEventResource,
    "icarWithdrawalEventResource": IcarWithdrawalEventResource,
    "icarFeedResource": IcarFeedResource,
    "icarFeedStorageResource": IcarFeedStorageResource,
    "icarFeedTransactionResource": IcarFeedTransactionResource,
    "icarFeedIntakeEventResource": IcarFeedIntakeEventResource,
    "icarFeedRecommendationResource": IcarFeedRecommendationResource,
    "icarFeedReportResource": IcarFeedReportResource,
    "icarRationResource": IcarRationResource,
    "icarGroupFeedingEventResource": IcarGroupFeedingEventResource,
    "icarReproAbortionEventResource": IcarReproAbortionEventResource,
    "icarReproDoNotBreedEventResource": IcarReproDoNotBreedEventResource,
    "icarReproEmbryoFlushingEventResource": IcarReproEmbryoFlushingEventResource,
    "icarReproEmbryoResource": IcarReproEmbryoResource,
    "icarReproHeatEventResource": IcarReproHeatEventResource,
    "icarReproMatingRecommendationResource": IcarReproMatingRecommendationResource,
    "icarReproParturitionEventResource": IcarReproParturitionEventResource,
    "icarReproPregnancyCheckEventResource": IcarReproPregnancyCheckEventResource,
    "icarReproSemenStrawResource": IcarReproSemenStrawResource,
    "icarReproStatusObservedEventResource": IcarReproStatusObservedEventResource,
    "icarGestationResource": IcarGestationResource,
    "icarLactationResource": IcarLactationResource,
    "icarLactationStatusObservedEventResource": IcarLactationStatusObservedEventResource,
    "icarMilkingDryOffEventResource": IcarMilkingDryOffEventResource,
    "icarDailyMilkingAveragesResource": IcarDailyMilkingAveragesResource,
    "icarMilkPredictionResource": IcarMilkPredictionResource,
    "icarTestDayResource": IcarTestDayResource,
    "icarTestDayResultEventResource": IcarTestDayResultEventResource,
    "icarCarcassResource": IcarCarcassResource,
    "icarCarcassObservationsEventResource": IcarCarcassObservationsEventResource,
    "icarBreedingValueResource": IcarBreedingValueResource,
    "icarProgenyDetailsResource": IcarProgenyDetailsResource,
    "icarGroupMovementBirthEventResource": IcarGroupMovementBirthEventResource,
    "icarGroupMovementArrivalEventResource": IcarGroupMovementArrivalEventResource,
    "icarGroupMovementDepartureEventResource": IcarGroupMovementDepartureEventResource,
    "icarGroupMovementDeathEventResource": IcarGroupMovementDeathEventResource,
    "icarPositionObservationEventResource": IcarPositionObservationEventResource,
    "icarGroupPositionObservationEventResource": IcarGroupPositionObservationEventResource,
    "icarDeviceResource": IcarDeviceResource,
    "icarMedicineResource": IcarMedicineResource,
    "icarMedicineTransactionResource": IcarMedicineTransactionResource,
    "icarLocationResource": IcarLocationResource,
    "icarInventoryTransactionResource": IcarInventoryTransactionResource,
    "icarObservationSummaryResource": IcarObservationSummaryResource,
    "icarProcessingLotResource": IcarProcessingLotResource,
    "icarStatisticsResource": IcarStatisticsResource,
    "icarSchemeTypeResource": IcarSchemeTypeResource,
    "icarSchemeValueResource": IcarSchemeValueResource,
    "icarSortingSiteResource": IcarSortingSiteResource,
    "icarAnimalSortingCommandResource": IcarAnimalSortingCommandResource,
    "icarConformationScoreEventResource": IcarConformationScoreEventResource,
    "icarTypeClassificationEventResource": IcarTypeClassificationEventResource,
}


def resolve_model(resource_type: str) -> Type[IcarResource]:
    return RESOURCE_MODEL_REGISTRY.get(resource_type, GenericIcarResource)


def is_registered(resource_type: str) -> bool:
    return resource_type in RESOURCE_MODEL_REGISTRY


def list_registered_types() -> list[str]:
    return list(RESOURCE_MODEL_REGISTRY.keys())
